// AUTO-GENERATED from ESPN /teams (browser-CORS-blocked, so baked in).
// Regenerate when soccer promotion/relegation changes rosters.
// [id, abbreviation, displayName]
export const ROSTERS: Record<string, [string, string, string][]> = {
  nfl: [
    ["22", "ARI", "Arizona Cardinals"],
    ["1", "ATL", "Atlanta Falcons"],
    ["33", "BAL", "Baltimore Ravens"],
    ["2", "BUF", "Buffalo Bills"],
    ["29", "CAR", "Carolina Panthers"],
    ["3", "CHI", "Chicago Bears"],
    ["4", "CIN", "Cincinnati Bengals"],
    ["5", "CLE", "Cleveland Browns"],
    ["6", "DAL", "Dallas Cowboys"],
    ["7", "DEN", "Denver Broncos"],
    ["8", "DET", "Detroit Lions"],
    ["9", "GB", "Green Bay Packers"],
    ["34", "HOU", "Houston Texans"],
    ["11", "IND", "Indianapolis Colts"],
    ["30", "JAX", "Jacksonville Jaguars"],
    ["12", "KC", "Kansas City Chiefs"],
    ["13", "LV", "Las Vegas Raiders"],
    ["24", "LAC", "Los Angeles Chargers"],
    ["14", "LAR", "Los Angeles Rams"],
    ["15", "MIA", "Miami Dolphins"],
    ["16", "MIN", "Minnesota Vikings"],
    ["17", "NE", "New England Patriots"],
    ["18", "NO", "New Orleans Saints"],
    ["19", "NYG", "New York Giants"],
    ["20", "NYJ", "New York Jets"],
    ["21", "PHI", "Philadelphia Eagles"],
    ["23", "PIT", "Pittsburgh Steelers"],
    ["25", "SF", "San Francisco 49ers"],
    ["26", "SEA", "Seattle Seahawks"],
    ["27", "TB", "Tampa Bay Buccaneers"],
    ["10", "TEN", "Tennessee Titans"],
    ["28", "WSH", "Washington Commanders"],
  ],
  mlb: [
    ["29", "ARI", "Arizona Diamondbacks"],
    ["11", "ATH", "Athletics"],
    ["15", "ATL", "Atlanta Braves"],
    ["1", "BAL", "Baltimore Orioles"],
    ["2", "BOS", "Boston Red Sox"],
    ["16", "CHC", "Chicago Cubs"],
    ["4", "CHW", "Chicago White Sox"],
    ["17", "CIN", "Cincinnati Reds"],
    ["5", "CLE", "Cleveland Guardians"],
    ["27", "COL", "Colorado Rockies"],
    ["6", "DET", "Detroit Tigers"],
    ["18", "HOU", "Houston Astros"],
    ["7", "KC", "Kansas City Royals"],
    ["3", "LAA", "Los Angeles Angels"],
    ["19", "LAD", "Los Angeles Dodgers"],
    ["28", "MIA", "Miami Marlins"],
    ["8", "MIL", "Milwaukee Brewers"],
    ["9", "MIN", "Minnesota Twins"],
    ["21", "NYM", "New York Mets"],
    ["10", "NYY", "New York Yankees"],
    ["22", "PHI", "Philadelphia Phillies"],
    ["23", "PIT", "Pittsburgh Pirates"],
    ["25", "SD", "San Diego Padres"],
    ["26", "SF", "San Francisco Giants"],
    ["12", "SEA", "Seattle Mariners"],
    ["24", "STL", "St. Louis Cardinals"],
    ["30", "TB", "Tampa Bay Rays"],
    ["13", "TEX", "Texas Rangers"],
    ["14", "TOR", "Toronto Blue Jays"],
    ["20", "WSH", "Washington Nationals"],
  ],
  nba: [
    ["1", "ATL", "Atlanta Hawks"],
    ["2", "BOS", "Boston Celtics"],
    ["17", "BKN", "Brooklyn Nets"],
    ["30", "CHA", "Charlotte Hornets"],
    ["4", "CHI", "Chicago Bulls"],
    ["5", "CLE", "Cleveland Cavaliers"],
    ["6", "DAL", "Dallas Mavericks"],
    ["7", "DEN", "Denver Nuggets"],
    ["8", "DET", "Detroit Pistons"],
    ["9", "GS", "Golden State Warriors"],
    ["10", "HOU", "Houston Rockets"],
    ["11", "IND", "Indiana Pacers"],
    ["12", "LAC", "LA Clippers"],
    ["13", "LAL", "Los Angeles Lakers"],
    ["29", "MEM", "Memphis Grizzlies"],
    ["14", "MIA", "Miami Heat"],
    ["15", "MIL", "Milwaukee Bucks"],
    ["16", "MIN", "Minnesota Timberwolves"],
    ["3", "NO", "New Orleans Pelicans"],
    ["18", "NY", "New York Knicks"],
    ["25", "OKC", "Oklahoma City Thunder"],
    ["19", "ORL", "Orlando Magic"],
    ["20", "PHI", "Philadelphia 76ers"],
    ["21", "PHX", "Phoenix Suns"],
    ["22", "POR", "Portland Trail Blazers"],
    ["23", "SAC", "Sacramento Kings"],
    ["24", "SA", "San Antonio Spurs"],
    ["28", "TOR", "Toronto Raptors"],
    ["26", "UTAH", "Utah Jazz"],
    ["27", "WSH", "Washington Wizards"],
  ],
  nhl: [
    ["25", "ANA", "Anaheim Ducks"],
    ["1", "BOS", "Boston Bruins"],
    ["2", "BUF", "Buffalo Sabres"],
    ["3", "CGY", "Calgary Flames"],
    ["7", "CAR", "Carolina Hurricanes"],
    ["4", "CHI", "Chicago Blackhawks"],
    ["17", "COL", "Colorado Avalanche"],
    ["29", "CBJ", "Columbus Blue Jackets"],
    ["9", "DAL", "Dallas Stars"],
    ["5", "DET", "Detroit Red Wings"],
    ["6", "EDM", "Edmonton Oilers"],
    ["26", "FLA", "Florida Panthers"],
    ["8", "LA", "Los Angeles Kings"],
    ["30", "MIN", "Minnesota Wild"],
    ["10", "MTL", "Montreal Canadiens"],
    ["27", "NSH", "Nashville Predators"],
    ["11", "NJ", "New Jersey Devils"],
    ["12", "NYI", "New York Islanders"],
    ["13", "NYR", "New York Rangers"],
    ["14", "OTT", "Ottawa Senators"],
    ["15", "PHI", "Philadelphia Flyers"],
    ["16", "PIT", "Pittsburgh Penguins"],
    ["18", "SJ", "San Jose Sharks"],
    ["124292", "SEA", "Seattle Kraken"],
    ["19", "STL", "St. Louis Blues"],
    ["20", "TB", "Tampa Bay Lightning"],
    ["21", "TOR", "Toronto Maple Leafs"],
    ["129764", "UTAH", "Utah Mammoth"],
    ["22", "VAN", "Vancouver Canucks"],
    ["37", "VGK", "Vegas Golden Knights"],
    ["23", "WSH", "Washington Capitals"],
    ["28", "WPG", "Winnipeg Jets"],
  ],
  mls: [
    ["18418", "ATL", "Atlanta United FC"],
    ["20906", "ATX", "Austin FC"],
    ["9720", "MTL", "CF Montréal"],
    ["21300", "CLT", "Charlotte FC"],
    ["182", "CHI", "Chicago Fire FC"],
    ["184", "COL", "Colorado Rapids"],
    ["183", "CLB", "Columbus Crew"],
    ["193", "DC", "D.C. United"],
    ["18267", "CIN", "FC Cincinnati"],
    ["185", "DAL", "FC Dallas"],
    ["6077", "HOU", "Houston Dynamo FC"],
    ["20232", "MIA", "Inter Miami CF"],
    ["187", "LA", "LA Galaxy"],
    ["18966", "LAFC", "LAFC"],
    ["17362", "MIN", "Minnesota United FC"],
    ["18986", "NSH", "Nashville SC"],
    ["189", "NE", "New England Revolution"],
    ["17606", "NYC", "New York City FC"],
    ["12011", "ORL", "Orlando City SC"],
    ["10739", "PHI", "Philadelphia Union"],
    ["9723", "POR", "Portland Timbers"],
    ["4771", "RSL", "Real Salt Lake"],
    ["190", "RBNY", "Red Bull New York"],
    ["22529", "SD", "San Diego FC"],
    ["191", "SJ", "San Jose Earthquakes"],
    ["9726", "SEA", "Seattle Sounders FC"],
    ["186", "SKC", "Sporting Kansas City"],
    ["21812", "STL", "St. Louis CITY SC"],
    ["7318", "TOR", "Toronto FC"],
    ["9727", "VAN", "Vancouver Whitecaps"],
  ],
  epl: [
    ["349", "BOU", "AFC Bournemouth"],
    ["359", "ARS", "Arsenal"],
    ["362", "AVL", "Aston Villa"],
    ["337", "BRE", "Brentford"],
    ["331", "BHA", "Brighton & Hove Albion"],
    ["363", "CHE", "Chelsea"],
    ["388", "COV", "Coventry City"],
    ["384", "CRY", "Crystal Palace"],
    ["368", "EVE", "Everton"],
    ["370", "FUL", "Fulham"],
    ["306", "HUL", "Hull City"],
    ["373", "IPS", "Ipswich Town"],
    ["357", "LEE", "Leeds United"],
    ["364", "LIV", "Liverpool"],
    ["382", "MNC", "Manchester City"],
    ["360", "MAN", "Manchester United"],
    ["361", "NEW", "Newcastle United"],
    ["393", "NFO", "Nottingham Forest"],
    ["366", "SUN", "Sunderland"],
    ["367", "TOT", "Tottenham Hotspur"],
  ],
  eflc: [
    ["392", "BIR", "Birmingham City"],
    ["365", "BLK", "Blackburn Rovers"],
    ["358", "BOL", "Bolton Wanderers"],
    ["333", "BRC", "Bristol City"],
    ["379", "BUR", "Burnley"],
    ["347", "CAR", "Cardiff City"],
    ["372", "CHA", "Charlton Athletic"],
    ["374", "DER", "Derby County"],
    ["314", "LCN", "Lincoln City"],
    ["369", "MID", "Middlesbrough"],
    ["391", "MIL", "Millwall"],
    ["381", "NOR", "Norwich City"],
    ["385", "POR", "Portsmouth"],
    ["394", "PNE", "Preston North End"],
    ["334", "QPR", "Queens Park Rangers"],
    ["398", "SHU", "Sheffield United"],
    ["376", "SOU", "Southampton"],
    ["336", "STK", "Stoke City"],
    ["318", "SWA", "Swansea City"],
    ["395", "WAT", "Watford"],
    ["383", "WBA", "West Bromwich Albion"],
    ["371", "WHU", "West Ham United"],
    ["380", "WOL", "Wolverhampton Wanderers"],
    ["352", "WXM", "Wrexham"],
  ],
  ligue1: [
    ["172", "AUX", "AJ Auxerre"],
    ["174", "MON", "AS Monaco"],
    ["7868", "ANG", "Angers"],
    ["6997", "BRE", "Brest"],
    ["3236", "HAC", "Le Havre AC"],
    ["2697", "MNS", "Le Mans"],
    ["175", "RCL", "Lens"],
    ["166", "LILL", "Lille"],
    ["273", "LOR", "Lorient"],
    ["167", "LYON", "Lyon"],
    ["176", "OLM", "Marseille"],
    ["2502", "NICE", "Nice"],
    ["6851", "PAR", "Paris FC"],
    ["160", "PSG", "Paris Saint-Germain"],
    ["169", "REN", "Stade Rennais"],
    ["180", "STR", "Strasbourg"],
    ["179", "TOU", "Toulouse"],
    ["170", "TRY", "Troyes"],
  ],
  laliga: [
    ["96", "ALA", "Alavés"],
    ["93", "ATH", "Athletic Club"],
    ["1068", "ATM", "Atlético Madrid"],
    ["83", "BAR", "Barcelona"],
    ["85", "CEL", "Celta Vigo"],
    ["90", "DEP", "Deportivo La Coruña"],
    ["3751", "ELC", "Elche"],
    ["88", "ESP", "Espanyol"],
    ["2922", "GET", "Getafe"],
    ["1538", "LEV", "Levante"],
    ["99", "MCF", "Málaga"],
    ["97", "OSA", "Osasuna"],
    ["87", "RAC", "Racing Santander"],
    ["101", "RAY", "Rayo Vallecano"],
    ["244", "BET", "Real Betis"],
    ["86", "RMA", "Real Madrid"],
    ["89", "RSO", "Real Sociedad"],
    ["243", "SEV", "Sevilla"],
    ["94", "VAL", "Valencia"],
    ["102", "VIL", "Villarreal"],
  ],
  bundesliga: [
    ["598", "FCU", "1. FC Union Berlin"],
    ["131", "B04", "Bayer Leverkusen"],
    ["132", "MUN", "Bayern Munich"],
    ["124", "DOR", "Borussia Dortmund"],
    ["268", "BMG", "Borussia Mönchengladbach"],
    ["125", "SGE", "Eintracht Frankfurt"],
    ["3841", "FCA", "FC Augsburg"],
    ["122", "KOE", "FC Cologne"],
    ["127", "HSV", "Hamburg SV"],
    ["2950", "M05", "Mainz"],
    ["11420", "RBL", "RB Leipzig"],
    ["126", "SCF", "SC Freiburg"],
    ["3307", "SCP", "SC Paderborn 07"],
    ["10388", "ELV", "SV Elversberg"],
    ["133", "S04", "Schalke 04"],
    ["7911", "TSG", "TSG Hoffenheim"],
    ["134", "VFB", "VfB Stuttgart"],
    ["137", "SVW", "Werder Bremen"],
  ],
  seriea: [
    ["103", "MIL", "AC Milan"],
    ["104", "ROMA", "AS Roma"],
    ["105", "ATA", "Atalanta"],
    ["107", "BOL", "Bologna"],
    ["2925", "CAG", "Cagliari"],
    ["2572", "COMO", "Como"],
    ["109", "FIO", "Fiorentina"],
    ["4057", "FRO", "Frosinone"],
    ["3263", "GEN", "Genoa"],
    ["110", "INT", "Internazionale"],
    ["111", "JUV", "Juventus"],
    ["112", "LAZ", "Lazio"],
    ["113", "LEC", "Lecce"],
    ["4007", "MON", "Monza"],
    ["114", "NAP", "Napoli"],
    ["115", "PAR", "Parma"],
    ["3997", "SAS", "Sassuolo"],
    ["239", "TOR", "Torino"],
    ["118", "UDI", "Udinese"],
    ["17530", "VEN", "Venezia"],
  ],
};
